# Copyright 2015, Perceivon Hosting Inc.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY PERCEIVON HOSTING INC. AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL PERCEIVON HOSTING INC. OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
- name: Append pf settings to rc.conf
  lineinfile: dest=/etc/rc.conf line={{ item.line }}
  with_items:
          - { line: "kld_list=\"pf\"" }
          - { line: "pf_enable=\"YES\"" }
  tags:
  - pf
  - pkg-server

- name: Check if pf is already loaded
  shell:  kldstat -q -m pf
  register: module_pf_loaded
  ignore_errors: yes
  tags:
  - pf
  - pkg-server
#- name: debug pf_nat_loaded
#  debug: var=pf_nat_loaded
#  tags:
#   - pf
- name: Load pf
  shell: kldload pf
  when: module_pf_loaded|failed
  tags:
  - pf
  - pkg-server
  notify: restart pf
- name: Deploy pf.conf
  template: src='pf.conf.j2' dest='/etc/pf.conf' mode=0640
  run_once: true
  tags:
  - pf
  - pkg-server
- name: Restart pf
  service: name=pf state=started enabled=yes
  tags:
  - pf
  - pkg-server
